name = "fitibit-auto-meal"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[observability]
[observability.logs]
enabled = false
head_sampling_rate = 1
invocation_logs = true
persist = true

[vars]
PORT = "8787"
BASE_URL = "https://fitibit-auto-meal.dogu757.workers.dev"

[[d1_databases]]
binding = "DB"
database_name = "fitbit-meal-logger-db"
database_id = "4d3e1657-bb03-4115-8e03-3141642cef56"

[env.production]

[[env.production.d1_databases]]
binding = "DB"
database_name = "fitbit-meal-logger-db"
database_id = "4d3e1657-bb03-4115-8e03-3141642cef56"
