name = "fitbit-meal-logger"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]


[vars]
PORT = "8787"
BASE_URL = "https://fitbit-meal-logger.dogu757.workers.dev"

[[d1_databases]]
binding = "DB"
database_name = "fitbit-meal-logger-db"
database_id = "4d3e1657-bb03-4115-8e03-3141642cef56"

[env.production]

[[env.production.d1_databases]]
binding = "DB"
database_name = "fitbit-meal-logger-db"
database_id = "4d3e1657-bb03-4115-8e03-3141642cef56"
